/* eslint-disable no-restricted-globals */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener('push', (event) => {
    let data = { title: 'New Update', body: 'You have a new notification from SLOOK.' };
    
    if (event.data) {
        try {
            data = event.data.json();
        } catch (err) {
            data = { title: 'New Update', body: event.data.text() };
        }
    }

    const options = {
        body: data.body,
        icon: '/pwa-192x192.png', // Update to your iconic path
        badge: '/pwa-192x192.png',
        data: data.data || {},
        vibrate: [100, 50, 100],
        actions: [
            { action: 'explore', title: 'View Now' },
            { action: 'close', title: 'Close' }
        ]
    };

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data.url || '/account/notifications';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window open with this URL
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});
